# This file was generated by GoReleaser. DO NOT EDIT.
cask "aspex" do
  version "0.8.1"

  on_macos do
    on_arm do
      sha256 "3d74e08a48a2afde0fdcc9f4ac6665f570dd3330d3caae3cda46951759170c7b"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff716675d5bbf0f604af73c4887500edb41fcf8beb044015230333007fea7291"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6d7dd87fadef168a6b9f6cf871b77ba33290d260922a09c7ca03291eea8467f6"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6a2fd86f9cf3dd0ac1012900fe3f7e88b047ac64e42c5dd5b0906636771ed5ab"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_amd64.tar.gz"
    end
  end

  name "aspex"
  desc "Local security debugger for AI agents: know what your agents can do, know what they actually did"
  homepage "https://github.com/aspex-security/aspex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aspex"
  binary "aspex-scan"
  binary "aspex-trace"
  binary "aspex-attack"
  binary "aspex-doctor"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-scan"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-trace"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-attack"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-doctor"]
    end
  end

  # No zap stanza required
end
