# This file was generated by GoReleaser. DO NOT EDIT.
cask "aspex" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "a532307eb1272300d2376642604a8f05517807d58c93e085e162b0dc7dc052cc"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "50ca55d8edd025859170fd40168012a6e815d371789ea1f1c6395ac6f5761692"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "23666971d0d31f30a0147e788aaceb43aedf2b8ca3f435ff8087d2000bb53a16"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6ef00fa963b7397e9e7fa3a72777a9afec3183c7ac1a6c1fe4f7e06776fe63ff"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_amd64.tar.gz"
    end
  end

  name "aspex"
  desc "Local security debugger for AI agents: know what your agents can do, know what they actually did"
  homepage "https://github.com/aspex-security/aspex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aspex"
  binary "aspex-scan"
  binary "aspex-trace"
  binary "aspex-attack"
  binary "aspex-doctor"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-scan"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-trace"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-attack"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-doctor"]
    end
  end

  # No zap stanza required
end
