# This file was generated by GoReleaser. DO NOT EDIT.
cask "aspex" do
  version "0.9.0"

  on_macos do
    on_arm do
      sha256 "f59e6fdbe539a973571da8a66fbdf2ec8d7d0b24d80ad4da4b0d53735c6cf8ec"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7454be6abb5e314addd7f8bd1015a79e2dd0da0468e90a57bee4fee5f7f321e8"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dbb732186ea6b2e43fab2ed5163c0cd6e5b79613594486e5e03f4b622d366fc0"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca0ab10df21408197d47891fa6aab22a7bb9232c32eb34666956b902f1806695"
      url "https://github.com/aspex-security/aspex/releases/download/v#{version}/aspex_linux_amd64.tar.gz"
    end
  end

  name "aspex"
  desc "Local security debugger for AI agents: know what your agents can do, know what they actually did"
  homepage "https://github.com/aspex-security/aspex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aspex"
  binary "aspex-scan"
  binary "aspex-trace"
  binary "aspex-attack"
  binary "aspex-doctor"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-scan"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-trace"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-attack"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/aspex-doctor"]
    end
  end

  # No zap stanza required
end
