# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aspex < Formula
  desc "AI Agent Security Toolkit: scan MCP servers and audit agent activity"
  homepage "https://github.com/aspex-security/aspex"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aspex-security/aspex/releases/download/v0.1.0/aspex_darwin_amd64.tar.gz"
      sha256 "5e41c981f3a4e5a7f5a7d57805ef7823b2ba77f36e99db99a4089b930d00c43c"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aspex-security/aspex/releases/download/v0.1.0/aspex_darwin_arm64.tar.gz"
      sha256 "e088f8d0fdefb2420e3723ab61aad35f23863b8329b84c23a95dc83962c5cf24"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.1.0/aspex_linux_amd64.tar.gz"
      sha256 "67fc5d779d50e43f4e2b49a548134428ca6adaa9d6818a4129ce6026fa0bea19"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.1.0/aspex_linux_arm64.tar.gz"
      sha256 "b3ef9b422863ec86960452abca629cddf2dd6bcf44303f7641d6ac159a5fbecb"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
      end
    end
  end

  test do
    system "#{bin}/aspex-scan version"
    system "#{bin}/aspex-trace version"
  end
end
