# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aspex < Formula
  desc "AI Agent Security Toolkit: scan MCP servers and audit agent activity"
  homepage "https://github.com/aspex-security/aspex"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aspex-security/aspex/releases/download/v0.5.3/aspex_darwin_amd64.tar.gz"
      sha256 "116de211fe4c9c0d2e8fce7ed7823ed910692bc45c069b4803b0d5b150268780"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
        bin.install "aspex-doctor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aspex-security/aspex/releases/download/v0.5.3/aspex_darwin_arm64.tar.gz"
      sha256 "1560835adf25df88028a764b63a6eb722110b122bf671d8378c484a4b2e04346"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
        bin.install "aspex-doctor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.5.3/aspex_linux_amd64.tar.gz"
      sha256 "9060412289b5a6f63f109e61898115a28592bdadae5cb72f8be6eb2214b55277"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
        bin.install "aspex-doctor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.5.3/aspex_linux_arm64.tar.gz"
      sha256 "1a963b50459440d52bda10f74b093108ec6b086c6e4e2dc2262c74b240bb689c"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
        bin.install "aspex-doctor"
      end
    end
  end

  def caveats
    <<~EOS
      Aspex is ready. Five commands are now available:

        aspex         - Interactive launcher (start here)
        aspex-scan    - Scan MCP server configs for security risks
        aspex-trace   - Audit AI agent activity from native client logs
        aspex-attack  - Red team MCP servers with adversarial probes
        aspex-doctor  - Health check your local AI agent setup

      ── QUICK START ────────────────────────────────────────────────
        aspex-scan                  Scan all MCP clients on this machine
        aspex-scan inspect github   Deep-inspect the 'github' server

        aspex-trace                 Audit the last 24 h of agent activity
        aspex-trace --since 7d      Audit the last 7 days

      ── FULL HELP ──────────────────────────────────────────────────
        aspex-scan --help
        aspex-trace --help

      ── COMMON WORKFLOWS ───────────────────────────────────────────
        # Save an HTML report
        aspex-scan --html ~/aspex-report.html

        # CI: exit 1 on any critical finding
        aspex-scan --fail-on critical

        # Detect suspicious agent behavior
        aspex-trace --suppress-noise --fail-on high

        # Learn a behavioral baseline, then detect deviations
        aspex-trace baseline --learn --since 7d
        aspex-trace --baseline ~/.config/aspex/aspex-trace-baseline.json

      No data is sent anywhere. Both tools run entirely offline.
    EOS
  end

  test do
    system "#{bin}/aspex-scan version"
    system "#{bin}/aspex-trace version"
    system "#{bin}/aspex-attack --version"
    system "#{bin}/aspex --version"
    system "#{bin}/aspex-doctor --version"
  end
end
