# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aspex < Formula
  desc "AI Agent Security Toolkit: scan MCP servers and audit agent activity"
  homepage "https://github.com/aspex-security/aspex"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aspex-security/aspex/releases/download/v0.4.0/aspex_darwin_amd64.tar.gz"
      sha256 "a16f75b94b556b928e05f3046b84374c30e8ff0def7e8a82b4b920569b1644b2"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aspex-security/aspex/releases/download/v0.4.0/aspex_darwin_arm64.tar.gz"
      sha256 "1ec4e9b8e7de2da617ff029d156c6a894513ff6d51cc901f1f14f36c65dcfd78"

      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.4.0/aspex_linux_amd64.tar.gz"
      sha256 "919bffb351510393c1520130f3c57729a99650dccdec1329ce52e4d2e266cf84"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aspex-security/aspex/releases/download/v0.4.0/aspex_linux_arm64.tar.gz"
      sha256 "52fd7159cde4fefdea4dfaa8dfe772ac864d812868dae142690a2a5cb7253551"
      define_method(:install) do
        bin.install "aspex-scan"
        bin.install "aspex-trace"
        bin.install "aspex-attack"
        bin.install "aspex"
      end
    end
  end

  def caveats
    <<~EOS
      Aspex is ready. Four commands are now available:

        aspex         — Interactive launcher (start here)
        aspex-scan    — Scan MCP server configs for security risks
        aspex-trace   — Audit AI agent activity from native client logs
        aspex-attack  — Red team MCP servers with adversarial probes

      ── QUICK START ────────────────────────────────────────────────
        aspex-scan                  Scan all MCP clients on this machine
        aspex-scan inspect github   Deep-inspect the 'github' server

        aspex-trace                 Audit the last 24 h of agent activity
        aspex-trace --since 7d      Audit the last 7 days

      ── FULL HELP ──────────────────────────────────────────────────
        aspex-scan --help
        aspex-trace --help

      ── COMMON WORKFLOWS ───────────────────────────────────────────
        # Save an HTML report
        aspex-scan --html ~/aspex-report.html

        # CI: exit 1 on any critical finding
        aspex-scan --fail-on critical

        # Detect suspicious agent behavior
        aspex-trace --suppress-noise --fail-on high

        # Learn a behavioral baseline, then detect deviations
        aspex-trace baseline --learn --since 7d
        aspex-trace --baseline ~/.config/aspex/aspex-trace-baseline.json

      No data is sent anywhere. Both tools run entirely offline.
    EOS
  end

  test do
    system "#{bin}/aspex-scan version"
    system "#{bin}/aspex-trace version"
    system "#{bin}/aspex-attack --version"
    system "#{bin}/aspex --version"
  end
end
